name: Build CLI

on:
  push:
    branches: [master, main]
    # tags:
    #   - "v*.*.*"

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Download nodejs binary
        run: |
          cd ..
          wget https://nodejs.org/download/release/v22.11.0/node-v22.11.0-linux-x64.tar.xz
          tar -xf node-v22.11.0-linux-x64.tar.xz
          cd -

      - name: Build CLI
        run: make build-ci

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 11-tts
